Hayoung/js
Road-of-CODEr/we-hate-js pull request #22
Opened 2020-12-19 09:23 UTC by hayoung0Lee

## 아래의 내용을 채워주세요

1. 공부한 내용의 분류: 자바스크립트 개념
2. 공부한 내용 요약: 데이터 타입과 실행 컨텍스트
3. 참고 자료 / 책(이미지/인용문 등을 사용하셨다면 출처를 꼭 사용하신 파일에 추가해 주세요!)
[코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)

2020-12-19 17:23 UTC, 1ilsang requested changes
기여 감사합니다. 아래 내용들 보시고 자유롭게 의견 주세요!

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/README.md
> +여기서는 [코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)를 읽고 다시한번 너무나도 중요한 Javascript의 기본기를 정리하는 곳입니다.
> 여기서는 [코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)를 읽고 다시한번 너무나도 중요한 Javascript의 기본기를 정리하는 곳입니다. 

[코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)의 JavaScript 기본기를 정리하는 곳입니다. 

는 어떨까요?

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/chapter1.md
> +Javascript가 기본형과 참조형 데이터를 어떻게 처리하는지, 왜 다른지를 알아보는 장입니다!!
Javascript 로 된 애들 JavaScript 로 변경해 주세요~

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/chapter1.md
> +        > 출처 : Hayoung's ppt based on [코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)
출처는 밑에 한번에 사용해 주시면 될거 같아요.

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/chapter1.md
> +   - 모든 데이터는 바이트 단위의 식별자(메모리 주솟값, memory address)를 통해 서로 구분하고 연결
주솟값 -> 주소값, memory address -> Memory address

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/chapter1.md
> +    ```
\```javascript

이렇게 명시해주시면 마크다운에서 자바스크립트로 인식해줘요. 나머지 애들도 수정 부탁드립니다.

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/chapter2.md
> +# 2장 실행 컨텍스트(execution context)
execution context -> Execution context

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/chapter2.md
> +실행 컨텍스트는 자바스크립트의 핵심 개념으로, 클로저를 사용하는 다른 언어에서도 유사한 개념을 사용하므로, 이를 잘 이해하면 개발자로서의 실력향상에 많은 도움이 되니 열심히 이해해봅시다!!
> 실행 컨텍스트는 자바스크립트의 핵심 개념으로, 클로저를 사용하는 다른 언어에서도 유사한 개념을 사용하므로,

쉼표 없어도 될거 같아요.

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/chapter2.md
> +  - eval() 함수 -> 이유는 모르지만 악마처럼 취급 받는다고 함
> 이유는 모르지만 악마처럼 취급 받는다고 함

코드를 그대로 실행시켜 버리기 때문에 보안에 치명적인 이슈가 있어요. [더 자세히](https://stackoverflow.com/questions/86513/why-is-using-the-javascript-eval-function-a-bad-idea)

이 내용을 추가해 주시면 좋을거 같네요.

2020-12-19 17:23 UTC, 1ilsang commented on JavaScript/concept/chapter2.md
> +    ```
복사붙여넣기 할때 보기 간편하도록 숫자를 주석으로 뒤에 넣으면 더 좋을거 같아요.

```javascript
let a = 1;            // 1
function outer() {   // 2
  function inner() {  // 3
    console.log(a);   // 4
    let a = 3;         // 5
  }                   // 6
  inner();             // 7
  console.log(a);      // 8
}                   // 9
outer();           // 10
console.log(a);       // 11
```

2020-12-20 03:10 UTC, hayoung0Lee commented on JavaScript/concept/README.md
> +여기서는 [코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)를 읽고 다시한번 너무나도 중요한 Javascript의 기본기를 정리하는 곳입니다.
코어 자바스크립트 다 정리하고 싶습니당!!! 구조 바꾸는게 좋겠네요!!!!

2020-12-20 03:10 UTC, hayoung0Lee commented on JavaScript/concept/chapter1.md
> +        > 출처 : Hayoung's ppt based on [코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)
넵!!!

2020-12-20 03:11 UTC, hayoung0Lee commented on JavaScript/concept/chapter2.md
> +    ```
아 뒷쪽에 넣는게 좋군요! 피드백 주신거 반영하도록 하겠습니다!!!

2020-12-20 07:14 UTC, 1ilsang commented on JavaScript/core/README.md
> +[코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)의 JavaScript 기본기를 정리하는 곳입니다.
고생하셨습니다! 요 부분만 지워주시면 될것 같아요. 이렇게되면 또 책을 정리한 느낌이라서요.

문서에서 책을 인용하는 방향으로 가는게 더 좋을것 같습니다!

2020-12-20 08:09 UTC, hayoung0Lee commented on JavaScript/core/README.md
> +[코어 자바스크립트](http://www.yes24.com/Product/Goods/78586788)의 JavaScript 기본기를 정리하는 곳입니다.
기존에 자바스크립트 폴더내의 README로 내용을 합쳤습니다! 확인 부탁드립니다!

2020-12-20 08:13 UTC, 1ilsang commented
고생하셨습니다. 다음에는 커밋도 신경써 보시면 좋을거 같아요. `feat(docs): Add Lexical Environment`

2020-12-20 08:13 UTC, merged