함수형 프로그래밍 추가
Road-of-CODEr/we-hate-js pull request #33
Opened 2021-03-02 13:36 UTC by ManHyuk

## 아래의 내용을 채워주세요

1. 공부한 내용의 분류 
     - 함수형 프로그래밍
2. 공부한 내용 요약
    -  함수형 프로그래밍 개론
3. 참고 자료 / 책(이미지/인용문 등을 사용하셨다면 출처를 꼭 사용하신 파일에 추가해 주세요!)
https://overcurried.com
https://www.inflearn.com/course/함수형_ES6_응용편
https://www.youtube.com/watch?v=jI4aMyqvpfQ&ab_channel=naverd2

내용 추가 및 수정중입니다~

2021-03-03 00:11 UTC, soobing requested changes
👍🏻 와 공부 많이 하셨네요~! Functor 부터는 이해가 잘 안되서 더 공부해보고 질문드릴께요!
오타 잡아보았습니다.

2021-03-03 00:11 UTC, soobing commented on JavaScript/fp.md
> +        return adjective + 'cool' + string;
실제로는 `coolcoolconference` 로 출력되고 있어요
```suggestion
        return adjective + ' ' + string;
```

2021-03-03 00:11 UTC, soobing commented on JavaScript/fp.md
> +        acc = f(acc, a);
오류가 나고 있어요!
```suggestion
        acc = f(acc, it);
```
Imperative programming이 더 이해하기는 쉽네요..😅

2021-03-03 00:11 UTC, soobing commented on JavaScript/fp.md
> +이를 해결하기 위해 `Persistane Data Structure` 를 사용하면 된다.
```suggestion
이를 해결하기 위해 `Persistent Data Structure` 를 사용하면 된다.
```

2021-03-03 00:11 UTC, soobing commented on JavaScript/fp.md
> +// 반복문을 사용한 일반적인 raange 함수
```suggestion
// 반복문을 사용한 일반적인 range 함수 
```

2021-03-03 00:11 UTC, soobing commented on JavaScript/fp.md
> +test('L.range', 10, () => reduce(add, L.range(10000))) // 200ms
예제 코드 보고 더 알쏭달쏭 해졌어요  ㅠ ㅠ
 `generator를 사용해 함수가 평가되기 직전까지 값이 만들어지지 않는다. (지연평가)`라고 했는데 왜 시간이 더 짧게 걸리는거죠?

2021-03-03 00:11 UTC, soobing commented on JavaScript/fp.md
> +만약에 String, List<String> 을 input으로 넣어도 잘 작동해야 한담면?
```suggestion
만약에 String, List<String> 을 input으로 넣어도 잘 작동해야 한다면?
```

2021-03-03 00:11 UTC, soobing commented on JavaScript/fp.md
> +```
오! 이런 예제도 추가되있으면 좋겠네요
```
const addAForArray = transFunctionForArray<number, string>(addA);

```

2021-03-03 00:11 UTC, soobing commented on JavaScript/fp.md
> +```java
이때부터 이해가 어렵... ㅎㅎ.....

2021-03-03 14:46 UTC, ManHyuk commented on JavaScript/fp.md
> +test('L.range', 10, () => reduce(add, L.range(10000))) // 200ms
지연평가라는 단어에서 `지연`은 시간의 `지연`이라기보다 값이 생성되는 시점을 `지연` 시킨다고 이해하면 좋을것 같습니다 👍

2021-03-03 14:47 UTC, ManHyuk commented on JavaScript/fp.md
> +```java
아직 펑터랑 모나드쪽은 내용 추가가 덜 되어서요 ㅎㅎ
최대한 쉽게 정리해보겠습니다

리뷰 감사합니다 ( _ _ )

2021-03-07 11:31 UTC, 1ilsang approved these changes

2021-03-07 11:31 UTC, 1ilsang approved these changes

2021-03-07 11:31 UTC, merged