feat: 마이크로 프론트엔드
Road-of-CODEr/we-hate-js pull request #39
Opened 2021-03-11 17:02 UTC by soobing

## 아래의 내용을 채워주세요

1. 공부한 내용의 분류
- `마이크로 프론트엔드` 개념에 대한 이해
2. 공부한 내용 요약
- 프론트엔드 레이어가 커지면서 비즈니스 로직에 맞게 팀마다 관리하는 프론트앤드 앱이 따로 구성된다. 각각의 팀에서 개발한 컴포넌트들을 하나의 앱에서 관리하기 위해서는 어떻게 해야하는가? 에 대한 이야기
- 결론 =  Custom Element를 두고 이벤트를 통해 서로 통신하게 하자.
3. 참고 자료 / 책(이미지/인용문 등을 사용하셨다면 출처를 꼭 사용하신 파일에 추가해 주세요!)
- https://micro-frontends.org/

2021-03-11 17:06 UTC, soobing commented on Front-End/Next.js/tips/micro-frontend.md
> +* __Custom APIs보다 기본 브라우저 기능 선호__<br>글로벌 PubSub 시스템을 구축하는 대신 [통신을 위한 브라우저 이벤트(Browser Events for communication)](#parent-child-communication--dom-modification)를 사용하자. 만약 당신이 정말로 크로스 팀 API를 구축해야 한다면,
`PubSub 시스템`이 뭔지 설명해주실분?

2021-03-11 17:06 UTC, soobing commented on Front-End/Next.js/tips/micro-frontend.md
> +#include로 시작하는 주석은 대부분의 웹 서버에서 사용할 수 있는 기능인  [Server Side Includes](https://en.wikipedia.org/wiki/Server_Side_Includes)의 일부다. 그렇다. 이것은 예전에 우리 웹사이트에 현재 날짜를 임베드 시키기 위해 사용했던 것과 같은 기술이다. [ESI](https://en
ESI, node esi 뭔지 아시는분..?

2021-03-11 18:21 UTC, 1ilsang commented on Front-End/Next.js/tips/micro-frontend.md
> +* __Custom APIs보다 기본 브라우저 기능 선호__<br>글로벌 PubSub 시스템을 구축하는 대신 [통신을 위한 브라우저 이벤트(Browser Events for communication)](#parent-child-communication--dom-modification)를 사용하자. 만약 당신이 정말로 크로스 팀 API를 구축해야 한다면,
https://rinae.dev/posts/why-every-beginner-front-end-developer-should-know-publish-subscribe-pattern-kr

2021-03-12 02:03 UTC, 1ilsang requested changes
`./ressources/` 내용들이 함께 첨부 안된것 같아요! 엑박이네요.

제가 아직 내용을 전체 다 읽은 내용은 아닌데요, 해당 내용은 Next.js 보단 포괄적인 FE 느낌 아닌가요? 상위 폴더로 올리는게 더 좋을것 같네요!
(ex. `Front-End/tips/...`)

만약 상위폴더로 올리시면 assets 폴더도 생성해서 이미지 첨부해 올려주세요! 
압축은 https://squoosh.app/ 을 활용하면 좋습니다.

내용 더 살펴보고 리뷰 달게요

2021-03-12 03:54 UTC, soobing commented
> `./ressources/` 내용들이 함께 첨부 안된것 같아요! 엑박이네요.
> 
> 제가 아직 내용을 전체 다 읽은 내용은 아닌데요, 해당 내용은 Next.js 보단 포괄적인 FE 느낌 아닌가요? 상위 폴더로 올리는게 더 좋을것 같네요!
> (ex. `Front-End/tips/...`)
> 
> 만약 상위폴더로 올리시면 assets 폴더도 생성해서 이미지 첨부해 올려주세요!
> 압축은 https://squoosh.app/ 을 활용하면 좋습니다.
> 
> 내용 더 살펴보고 리뷰 달게요

폴더 구조 수정했습니다! 
압축도 해야하나요...? 이미지 하나하나요??

2021-03-12 12:23 UTC, 1ilsang requested changes
내용 정말 재밌게 읽었습니다!

중간중간 링크 및 마크다운 깨진 부분 추가한것 말고는 내용에 큰 이상없었습니다. 흥미로웠어요.

assets 를 전역에서 분기를 태우지 말고 tips 에서 사용되는 애들은 여기로 밀어주는게 어떨까요?

개인적으로는 여기에 해당 글이 길고, 정적 데이터가 많으므로 `Front-end/tips/micro-frontend/assets` 로 가고 글을 `readme.md` 로 지정해도 좋을듯 합니다.

만약 해당 글이 길어서 분리할 예정이시라면 readme 말고 세분화 해도 좋겠네요.

또한 500kb 가 넘는 이미지는 정당한 이미지인지(화질 및 width 가 오버스펙은 아닌지) 한번 확인이 필요할 것 같습니다. 용량을 훨씬 적게 사용할 수  있을 것 같아요.

고생하셨습니다!

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +* __기술 불가지론자(agnostic)__<br>각 팀은 다른 팀과 조정하지 않고도 기술 스택을 선택하고 업그레이드할 수 있어야 한다. [Custom Elements](#the-dom-is-the-api)는 구현 세부 정보를 숨기면서 다른 사용자에게 중립적인 인터페이스를 제공하는 좋은 방법이다.
`the-dom-is-the-api` 링크가 잘못되어 있네요. `DOM은 API다` 로 가야할것 같아요.

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +**여러 팀이 각자 독립적으로 기능(features)을 제공**할 수 있게 **모던 웹 앱 구축**을 위한 기술(Techniques), 전략(strategies), 레시피(recipes)에 관한 이야기.
첫 문자를 대문자로 갈거면 모두 대문자, 소문자로 할거면 모두 소문자로 맞춰주면 좋을것 같아요.

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +Micro Frontends는 개별 팀들이 소유하고있는 웹사이트나 웹앱을 하나의 기능으로 보고, **그 기능(features)을 구성(composition)** 하자는 방식의 아이디어 이다. 각 팀 별로 팀에서 담당하는 뚜렷한 **비즈니스 영역** 혹은  **미션**이 있을 것이다. 각 팀내 에서는 데이터베이스에서 사용자 인터페이스에 이르기까지 **상호
> **상호 기능(cross functional)**을 통해

괄호와 같이 사용하게 되면 마크다운이 먹혀요. 띄어쓰기가 필요해 보입니다.

- **상호 기능(cross functional)** 을 통해

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +![Monolithic Frontends](../../assets/images/micro-frontend/monolith-frontback-microservices.png)
에셋 위치 바꾼다면 패스 변경 한번 더 부탁드리겠습니다 (_ _)

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +[try in browser](./1-composition-client-only/) & [inspect the code](https://github.com/neuland/micro-frontends/tree/master/1-composition-client-only)
여기랑 위의 gif 클릭 링크가 안맞는거 같아요

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +[try in browser](./0-model-store/) & [inspect the code](https://github.com/neuland/micro-frontends/tree/master/0-model-store)
여기랑 위의 gif 클릭 링크가 안맞는거 같아요

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +예제에서 이 페이지는 세개의 팀이 별도로 소유한 components/fragments로 분할 된다. 이제 **구매 버튼**과 **장바구니**와 같은 구매 프로세스와 관련된 모든 책임은 **Checkout팀 (파란색)**이 가지고 있다고 하자. **Inspire팀 (녹색)**은 이 페이지의 **추천 제품**을 관리한다. 페이지 자체는 **Product팀 (
괄호가 들어간 bold 작업은 뒤에 띄어쓰기를 붙여주세요.

>  **Checkout팀 (파란색)**이
-  **Checkout팀 (파란색)** 이

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +    window.customElements.define('blue-buy', BlueBuy);
코드 MD 타입을 명확히 지정해 주는건 어떨까요?

```js
console.log('This is js code template!);
```

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +To avoid duplication a `render()` method is introduced which is called from `connectedCallback` and `attributeChangedCallback`. This method collects needed data and innerHTML's the new markup. When d
잘못 추가되었네요

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +위의 예에서는 현재 [Chrome, Safari 및 Opera에서 지원](http://caniuse.com/#feat=custom-elementsv1)되는 Custom Element V1 Spec을 사용한다. 그러나 [document-register-element](https://github.com/WebReflection/document-register
Under the hood 는 의도적으로 놔두신 걸까요?

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +    window.customElements.define('blue-buy', BlueBuy);
> \```js

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +위의 예에서는 현재 [Chrome, Safari 및 Opera에서 지원](http://caniuse.com/#feat=custom-elementsv1)되는 Custom Element V1 Spec을 사용한다. 그러나 [document-register-element](https://github.com/WebReflection/document-register
> 백그라운드에서 해킹된 DOM 트리가 발견될 경우는 없다.

이게 해킹에 관련된 내용이 아니라 옵저버를 사용하고 있으니 자식 DOM 의 변경을 기다릴 필요 없다는 뜻 아닌가요?

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +DOM 메소드를 호출하는 것은 매우 드물지만, [video element api](https://developer.mozilla.org/de/docs/Web/HTML/Using_HTML5_audio_and_video#Controlling_media_playback)에서 예시를 볼 수 있다. 가능하면 선언적(declarative) 접근법인 속성 변경하는 방
링크가 깨졌네요. 여기일듯 합니다.

- https://developer.mozilla.org/ko/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content#Controlling_media_playback

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +Custom Elements는 브라우저 내의 컴포넌트를 통합하는 데 유용하다. 그러나 웹에서 접속 가능한 사이트를 구축할 때 초기 load performance가 문제될 가능성이 있고 모든 js 프레임워크가 다운로드되고 실행될 때까지 사용자는 흰색 화면을 볼 수 있다. 또한 JavaScript가 실패하거나 차단될 경우 사이트에 어떤 일이 발생할지 생각해
Eeements 오타네요

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +#include로 시작하는 주석은 대부분의 웹 서버에서 사용할 수 있는 기능인  [Server Side Includes](https://en.wikipedia.org/wiki/Server_Side_Includes)의 일부다. 그렇다. 이것은 예전에 우리 웹사이트에 현재 날짜를 임베드 시키기 위해 사용했던 것과 같은 기술이다. [ESI](https://en
이 부분이 좀 어려운데요, 

```js
// JSP(Java)
<jsp:include page="abc.jsp" flush="false" />

// Jade(Express)
include common/util

body
   include layout/header
   div#contents
   include layout/footer
```

제가 이해하기엔 Express 같은 서버에서 Jade 와 비슷한 렌더링 템플릿으로 HTML 을 조합해 내려줄 때 사용하는 방법을 프로젝트 단위가 아닌 서버 단위로 올린 개념을 뜻하는것 같네요.

각각의 페이지가 서로 다른 서버에서 렌더링되어서 와야하므로, iframe 과 같이 외부 페이지를 가져와야 한다는 뜻이 되는데 이걸 어떻게 해결할 것인가? 에 대한 답인것 같아요.

- https://medium.com/@clifcunn/nodeconf-eu-29dd3ed500ec

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +이 애니메이션은 **JavaScript가 비활성화(disabled)**된 트랙터 스토어 사이트를 보여준다.
bold 처리 부탁드려요

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +[![Serverside Rendering - Disabled JavaScript](../../assets/video/micro-frontend/micro-frontend/server-render.gif)](../../assets/video/micro-frontend/micro-frontend/server-render.mp4)
micro-frontend 가 두번 들어갔네요. 경로 수정 부탁드려요

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +Docker는 포트 3000에서 nginx를 시작하고 각 팀에 대해 node.js 이미지를 구축한다. 브라우저에서 [http://127.0.0.1:3000/](http://127.0.0.1:3000/)을 열면 빨간색 트랙터를 볼 수 있다. [Docker Compose](https://docs.docker.com/compose/install/)의 결합(co
오 무친ㅋㅋ 진짜 신기하네용

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +<img alt="Reflow" src="../../assets/video/micro-frontend/micro-frontend/data-fetching-reflow.gif" style="width: 500px" />
여기도 micro-frontend 가 두번 들어갔네요. 링크 수정 부탁드립니다.

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +렌더링 작업은 브라우저에서만 수행된다. 하지만, 애니메이션에서 볼 수 있듯이, 이 변화는 이제 페이지의 **상당한 반향(substantial reflow)**을 가져왔다. 추천 영역이 처음에는 비어있다. green 팀의 JavaScript가 로드되고 실행된다. 개인화된 권장 사항을 가져오기 위한 API 호출이 수행된다. 그리고 추천 영역 마크업이 렌더되고
bold 처리 부탁드립니다

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +<img alt="Skeleton Screen" src="../../assets/video/micro-frontend/micro-frontend/data-fetching-skeleton.gif" style="width: 500px" />
micro-frontend 링크 처리 부탁드립니다

2021-03-12 12:23 UTC, 1ilsang commented on Front-End/tips/micro-frontend.md
> +__to be continued soon ... (I promise)__
빨리 다음편 주세요 현기증나요

2021-03-12 12:27 UTC, 1ilsang commented
수빈님 글 보면서 도움 됐던 링크

2021-03-15 13:47 UTC, soobing commented
@1ilsang 50KB 넘는거는 리사이징 했는데 더이상하면 이미지가 너무 깨져서 냅두도록 하겠습니다~

2021-03-21 14:37 UTC, merged