feat(javascript): Add Javascript history
Road-of-CODEr/we-hate-js pull request #46
Opened 2021-03-16 06:27 UTC by hayoung0Lee

## 아래의 내용을 채워주세요

1. 공부한 내용의 분류
JavaScript
2. 공부한 내용 요약
JavaScript 의 역사
3. 참고 자료 / 책(이미지/인용문 등을 사용하셨다면 출처를 꼭 사용하신 파일에 추가해 주세요!)
모던 자바스크립트 DeepDive 2장

2021-03-16 06:31 UTC, hayoung0Lee commented
모던 자바스크립트 2장을 이렇게 정리해봤는데, 여기서 나오는 각 버전마다 추가된 문법같은건 아예 따로 빼서 정리하는게 좋을까요? jsHistory에 포함했습니다. 피드백 부탁드려요!

2021-03-17 11:46 UTC, 1ilsang requested changes
고생하셨습니다

2021-03-17 11:46 UTC, 1ilsang commented on JavaScript/jsHistory.md
> +JavaScript는 1995년 당시 시장 점유율이 90프로이던 Netscape communications가 `브라우저에서 동작하는 것을 목표`로 [`Brendan Eich`](https://en.wikipedia.org/wiki/Brendan_Eich)가 개발한 언어이다. JavaScript는 Brendan Eich씨가 10일간 걸려서 만든 JavaSc
>  JavaScript는

두 번 반복되고 있습니다.

2021-03-17 11:46 UTC, 1ilsang commented on JavaScript/jsHistory.md
> +- 그리고 2015에 범용 프로그래밍 언어가 갖춰야할 기능들인 `let/const, arrow function, class, module`등을 갖춘 ECMAScript 6(ES6)가 공개 되었다. 이 이후에는 매해 기능을 변경해서 발표하고 있다.
> ECMAScript 6

ECMAScript6 로 해주세요 ㅎㅎㅋ

2021-03-17 13:38 UTC, 1ilsang approved these changes
LGTM

2021-03-21 07:08 UTC, merged